### ISSUE TITLE
v2.1.0 TypeError: Cannot read property '_tag' of undefined

### ISSUE THREAD

**Issue by uhlryk** [blainekasten/enzyme-matchers#55]
One our test works correctly with your enzyme-matchers in **v2.0.0**. But in version **2.1.0** it stats failing.
Error doesn't look like a problem with test, it looks more like problem with enzyme-matchers.
Error stack trace:
```
TypeError: Cannot read property '_tag' of undefined
      at node_modules/enzyme-matchers/lib/utils/html.js:16:57
      at Array.map (native)
      at mapWrappersHTML (node_modules/enzyme-matchers/lib/utils/html.js:15:24)
      at printHTMLForWrapper (node_modules/enzyme-matchers/lib/utils/html.js:53:21)
      at Assertion.toBePresent (node_modules/enzyme-matchers/lib/assertions/toBePresent.js:32:73)
      at Assertion.<anonymous> (test/frontend/__helpers/assertions.js:12:43)
      at Assertion.Object.defineProperty.value [as bePresent] (node_modules/should/lib/assertion.js:147:14)
      at Context.<anonymous> (test/frontend/unit/features/appsList/appSuggestion/AppSuggestion.jsx:96:60)
```

Failing assertion looks:
```
wrapper.find(".appSuggestion .section").should.bePresent();
```

We use `should` for assertions and therefore I wrote wrapper which extends `should` with your module.

For us simplest solution is to downgrade to 2.0.0 and don't allow to update.

**Comment by blainekasten** [comment]
can you provide your code for what `wrapper` is?

**Comment by uhlryk** [comment]
Sure:
```
            const wrapper = mount(
                <Provider store={store}>
                    <AppSuggestion />
                </Provider>
            );
```

And AppSuggestion is `Higher Order Component`. Which wrap component created as function.

**Comment by blainekasten** [comment]
Can you show me the component code for AppSuggestion? Just trying to figure out where the bug is.

**Comment by uhlryk** [comment]
about this line : 
```
//at node_modules/enzyme-matchers/lib/utils/html.js:16:57
var type = node.type || node._reactInternalComponent._tag;
```
`node` has value:
```
HTMLParagraphElement {
  '__reactInternalInstance$ssjn9v96oprv0a4i': 
   ReactDOMComponent {
     _currentElement: 
      { '$$typeof': Symbol(react.element),
        type: 'p',
        key: null,
        ref: null,
        props: [Object],
        _owner: [Object],
        _store: {} },
     _tag: 'p',
     _namespaceURI: 'http://www.w3.org/1999/xhtml',
     _renderedChildren: null,
     _previousStyle: null,
     _previousStyleCopy: null,
     _hostNode: [Circular],
     _hostParent: 
      ReactDOMComponent {
        _currentElement: [Object],
        _tag: 'div',
        _namespaceURI: 'http://www.w3.org/1999/xhtml',
        _renderedChildren: [Object],
        _previousStyle: null,
        _previousStyleCopy: null,
        _hostNode: [Object],
        _hostParent: [Object],
        _rootNodeID: 27,
        _domID: 6,
        _hostContainerInfo: [Object],
        _wrapperState: null,
        _topLevelWrapper: null,
        _flags: 1,
        _ancestorInfo: [Object],
        _contentDebugID: null,
        _mountIndex: 0,
        _mountImage: null,
        _debugID: 63 },
     _rootNodeID: 28,
     _domID: 7,
     _hostContainerInfo: 
      { _topLevelWrapper: [Object],
        _idCounter: 13,
        _ownerDocument: [Object],
        _node: HTMLDivElement {},
        _tag: 'div',
        _namespaceURI: 'http://www.w3.org/1999/xhtml',
        _ancestorInfo: [Object] },
     _wrapperState: null,
     _topLevelWrapper: null,
     _flags: 1,
     _ancestorInfo: 
      { current: [Object],
        formTag: null,
        aTagInScope: null,
        buttonTagInScope: null,
        nobrTagInScope: null,
        pTagInButtonScope: [Object],
        listItemTagAutoclosing: null,
        dlItemTagAutoclosing: null },
     _contentDebugID: -64,
     _mountIndex: 0,
     _mountImage: null,
     _debugID: 64 } }
```

Interesting is that before this failing test we test this component with different params and all works great (we use there also toBePresent/bePresent).

In addition this failing component has other assertions which works ok. Only this one assertion throws this error.

```
wrapper.find(".appSuggestion .section")
```
has value:
```
ReactWrapper {
  component: null,
  root: 
   ReactWrapper {
     component: 
      { setChildProps: [Object],
        setChildContext: [Object],
        getInstance: [Object],
        getWrappedComponent: [Object],
        props: [Object],
        context: {},
        refs: {},
        updater: [Object],
        state: [Object],
        _reactInternalInstance: [Object] },
     root: [Circular],
     node: 
      Provider {
        props: [Object],
        context: {},
        refs: {},
        updater: [Object],
        store: [Object],
        _reactInternalInstance: [Object],
        state: null },
     nodes: [ [Object] ],
     length: 1,
     options: {},
     complexSelector: 
      ComplexSelector {
        buildPredicate: [Function: buildInstPredicate],
        findWhereUnwrapped: [Function: findWhereUnwrapped],
        childrenOfNode: [Function: childrenOfInst] } },
  node: 
   HTMLParagraphElement {
     '__reactInternalInstance$7hbdb77pl85s714i': 
      ReactDOMComponent {
        _currentElement: [Object],
        _tag: 'p',
        _namespaceURI: 'http://www.w3.org/1999/xhtml',
        _renderedChildren: null,
        _previousStyle: null,
        _previousStyleCopy: null,
        _hostNode: [Circular],
        _hostParent: [Object],
        _rootNodeID: 28,
        _domID: 7,
        _hostContainerInfo: [Object],
        _wrapperState: null,
        _topLevelWrapper: null,
        _flags: 1,
        _ancestorInfo: [Object],
        _contentDebugID: -64,
        _mountIndex: 0,
        _mountImage: null,
        _debugID: 64 } },
  nodes: 
   [ HTMLParagraphElement { '__reactInternalInstance$7hbdb77pl85s714i': [Object] },
     HTMLParagraphElement { '__reactInternalInstance$7hbdb77pl85s714i': [Object] } ],
  length: 2,
  options: {},
  complexSelector: 
   ComplexSelector {
     buildPredicate: [Function: buildInstPredicate],
     findWhereUnwrapped: [Function: findWhereUnwrapped],
     childrenOfNode: [Function: childrenOfInst] } }
```

Component has a lot of abstraction, If I show it it will not be useful.

**Comment by uhlryk** [comment]
It looks like that only this failing test reach 
```
function mapWrappersHTML
```

Looking on this function:
```
function printHTMLForWrapper(wrapper)
```
code will reach mapWrappersHTML if it has more then one node and fails. Very deep in test component there is 

```
        <CustomModal  >
            <p className="section">

            </p>
            <p className="section">

            </p>
        </CustomModal>
```
And it fails on it. If I remove one <p> then everything starts working

But I have in different places components with more then one child nodes and they works.

**Comment by blainekasten** [comment]
I'm having a hard time reproducing this. So the `mapWrappersHTML` gets called when the function is given more than 1 node: https://github.com/blainekasten/enzyme-matchers/blob/master/packages/enzyme-matchers/src/utils/html.js#L36

Which you are doing here by giving it both `p.section` nodes.

I definitely understand where the error is, but without finding a minimal reproducible test case, I can't confidently push a fix. Do you think you could work to minimize your component to what is actually causing the break so I can get a stable fix?

**Comment by uhlryk** [comment]
Hey
At Monday I will try find time to create simplest working example. But it looks like some anomaly rather then normal behavior, therefore I don't know if I accomplish this. Maybe you could push your changes on different branch and I will apply it to my code and tell you result?

**Comment by blainekasten** [comment]
I think I figured this out. Can you test `2.1.1-rc1` ?

**Comment by uhlryk** [comment]
Great! I updated to this version and it works

**Comment by blainekasten** [comment]
Awesome! I'll release soon!
